# frozen_string_literal: true

RSpec.describe DiscordChatBridge::Discord::AvatarUrl do
  it "accepts only the exact Discord CDN avatar shapes generated by the bridge" do
    expect(
      described_class.valid?("https://cdn.discordapp.com/avatars/1/a_hash.png?size=128"),
    ).to eq(true)
    expect(
      described_class.valid?(
        "https://cdn.discordapp.com/guilds/1/users/2/avatars/hash.png?size=128",
      ),
    ).to eq(true)
    expect(described_class.valid?("http://cdn.discordapp.com/avatars/1/hash.png?size=128")).to eq(
      false,
    )
    expect(described_class.valid?("https://cdn.discordapp.com/attachments/1/2/file.png")).to eq(
      false,
    )
  end

  it "accepts Discord's six default avatars" do
    expect(described_class.valid?("https://cdn.discordapp.com/embed/avatars/5.png")).to eq(true)
    expect(described_class.valid?("https://cdn.discordapp.com/embed/avatars/6.png")).to eq(false)
  end
end
